# This file was generated by GoReleaser. DO NOT EDIT.
cask "migrail" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "42985b1959c7c90cfb6e31e420ff7c5a0f6b23492a2185059039d0f7ca883ae1"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c40a18bb4210e1ebec12251a867016c3fcced5cea44882885c9ead7ccb8d1a7f"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "471f186bfa6a95398ead238d23a94c44928c6385bfe60698f36b605b38510b8e"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b743c53296f5858b3b9716c940b1e50a1a60d7275145a805bacad9978931d1ca"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_linux_amd64.tar.gz"
    end
  end

  name "migrail"
  desc "Catch dangerous database migrations before they reach production"
  homepage "https://github.com/bbrainttech/migrail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migrail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/migrail"]
    end
  end

  # No zap stanza required
end
