# This file was generated by GoReleaser. DO NOT EDIT.
cask "migrail" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "57649bb8cc52c1972a0b003573ccb7e67c45e4d8f45411b5566fc68fbf01a15b"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "71c0951112f68b1006f7637a02550b0a05b28f3e7ad8bcf1d2881a16f0c0ac95"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2e0d78ac65bc5e2e6d430ca4f8506e633c09b04be4e71503a718888aac017b32"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6e990b9b5569d7ec0cb1ae9ca0812da1cafe104b0603ed4a0577f27df1fa54fa"
      url "https://github.com/bbrainttech/migrail/releases/download/v#{version}/migrail_#{version}_linux_amd64.tar.gz"
    end
  end

  name "migrail"
  desc "Catch dangerous database migrations before they reach production"
  homepage "https://github.com/bbrainttech/migrail"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "migrail"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/migrail"]
    end
  end

  # No zap stanza required
end
